#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

SCRIPT_DIR_NAME="$(basename $(pwd))"
touch "$SCRIPT_DIR_NAME".foam""

runApplication setFields

## Parallel
runApplication decomposePar

runParallel foamRun

runApplication reconstructPar -latestTime

runApplication -s mySampling foamPostProcess -latestTime -func mySampleDict

#------------------------------------------------------------------------------
